_target_: manylatents.algorithms.latent.multi_dimensional_scaling.MDSModule
n_components: 2
random_state: ${seed}
how: metric   #  choose from ['classic', 'metric', 'nonmetric']
solver: smacof  # choose from ["sgd", "smacof"]
distance_metric: euclidean  # recommended values: 'euclidean' and 'cosine'
n_jobs: -1
verbose: False
fit_fraction: 1.0
n_landmark: null
random_landmarking: false
